deployment:
  tasks:
    - export APP_PATH=/home/tutreqhl/public_html/core
    - cd $APP_PATH

    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - php artisan migrate --force
    - php artisan cache:clear
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:clear
